### PR TITLE
Fix some words

### PR DESCRIPTION
**Pull request by co63oc**
Fix some words

### CODE REVIEW

**Review by kcxain — APPROVED** [review]

**Review by tastelikefeet — COMMENTED** [review]
The CI test failed because the code format is not correct. Could you please run 'pre-commit run --all-files' and submit the code?
Please run `pip install pre-commit` if it's not installed.

**Comment by co63oc** [comment]
> The CI test failed because the code format is not correct. Could you please run 'pre-commit run --all-files' and submit the code? Please run `pip install pre-commit` if it's not installed.

Thanks, I will do that

**Comment by co63oc** [comment]
图片

Cannot view the details of the unittest error， no expand button

**Comment by co63oc** [comment]
Cannot view the details of the unittest error, no expand button
图片

**Review by tastelikefeet — APPROVED** [review]

**Pull request merged**
